from payment_engine.repositories.sqlite_payment_repository import SQLitePaymentRepository

payment_repository = SQLitePaymentRepository()

from payment_engine.repositories.payment_event_repository import PaymentEventRepository

payment_event_repository = PaymentEventRepository()
