name: Swift Payment Engine CI

on:
  push:
    branches:
      - main
      - master
      - feature/v2.1.0

  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y mupdf-tools

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Compile
        run: |
          python -m compileall payment_engine

      - name: Run Tests
        run: |
          python -m unittest discover tests
